### ISSUE TITLE
Fail to load the page

### ISSUE THREAD

**Issue by xhsux** [takashiro/bezier-werewolf-react-archived#1]
Appearing the notification 'loadibg resources' on my oneplus 3t device

**Comment by takashiro** [comment]
Haha~ Fixed by commit https://github.com/takashiro/OneNightWerewolf/commit/50043ba32969d191f1219ca377a30878a0ab80d4

Root Cause: Some browsers may not support ES6, TextDecoder and TextEncoder.
How to Fix: 
1. Convert ES6 into ES5 with BabelJS and deploy a compatible version at http://onuw.takashiro.me/compat
2. Load polyfill of TextDecoder and TextEncoder.
